config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:new, :create] do
    collection do
      get 'finish'
    end
  end

  root 'videos#index'

  resources :videos, only: [:index, :show] do
    collection do
      get 'feed'
    end
  end

  resources :idols, only: [:index, :show] do
    collection do
      get 'search'
    end
  end
end

app/views/shared/_lower_ad.html.slim
.row#lower-ad
  h2.h5 グラビアBOX動画おすすめ商品
  - @lower_ads.each do |ad|
    .col.s6.m4.l3
      .card
        .card-image.waves-effect.waves-block.waves-light
          = link_to ad[:affiliateURL], target: "_blank" do
            = image_tag(ad[:imageURL][:small], alt: ad[:title], class: 'activator')
        .card-action
          = link_to(ad[:title], ad[:affiliateURL])
          br
          span.red-text
            = "価格: #{ad[:prices][:price]}円"

app/views/shared/_sidebar.html.slim
.col.s12.m12.l10
  .search-pc
    = form_tag(search_idols_path, method: "get", class: "search-form") do
      .input-field.inline.col.l9
        = text_field_tag 'search', ''
        label for="search"
          | グラドル名
        button.btn.btn-small.btn-search type="submit" name="action"
          i.material-icons
            | search

  #idol-list
    h3.h6 グラビアBOX動画登録アイドル
    .tags
      - @idols.each do |idol|
        = link_to idol.name, idol_path(idol), class: "waves-effect waves-light btn-flat red lighten-2"
      br
      = link_to "すべて見る", idols_path, class: "right-link"
  .advertisement
    == render "shared/sidebar_affiliate"
  #video-ranking
    h3.h6 グラビアBOX動画ランキング
    ul.collection
      - @popular_videos.each do |video|
        li.collection-item.avatar
          = image_tag("#{video.thumbnail}", alt: video_alt(video), class: 'responsive-img circle')
          = link_to(truncate(video.title, length: 25), video, class: "collection-link")
          - idol_names = video.idol_names
          - if idol_names.present?
            br
            - idol_names.each do |idol_name|
              .chip.mt10.red.lighten-2.white-text
                = idol_name

app/views/shared/_sidebar_affiliate.html.erb
<% if request_pc? %>
  <a href="http://www.dmm.co.jp/digital/videoa/-/list/=/article=keyword/id=6565/sort=ranking/nonpro0111-002" target="_blank"><img src="http://pics.dmm.com/af/a_digi_video_sale001/300_250.jpg" width="300" height="250" alt="アダルト　期間限定セール(毎週作品更新)" border="0"></a>
  <a href="http://www.dmm.co.jp/digital/videoa/nonpro0111-002" target="_blank"><img src="http://pics.dmm.com/af/a_digi/300_250.jpg" width="300" height="250" alt="アダルト動画" border="0"></a>
<% else %>
  <script type="text/javascript">
  var nend_params = {"media":43791,"site":237336,"spot":685056,"type":1,"oriented":1};
  </script>
  <script type="text/javascript" src="https://js1.nend.net/js/nendAdLoader.js"></script>
<% end %>