config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:new, :create] do
    collection do
      get 'finish'
    end
  end

  root 'videos#index'

  resources :videos, only: [:index, :show] do
    collection do
      get 'feed'
    end
  end

  resources :idols, only: [:index, :show] do
    collection do
      get 'search'
    end
  end
end

app/views/layouts/_google_analytics.html.slim
javascript:
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-23034091-15', 'auto');
  ga('send', 'pageview');

app/views/layouts/_meta_tags.html.slim
meta charset='UTF-8'
meta content='NOYDIR' name='ROBOTS'
meta content='NOODP' name='ROBOTS'

ruby:
  keywords = 'グラビアBOX,グラビア,動画,イメージビデオ,エロい,かわいい,美女,美少女,巨乳,微乳,ビキニ,水着,グラビアアイドル'
  site_name = 'グラビアBOX動画　〜グラビアアイドル動画見放題〜'
  if video
    description = "#{video.title}。#{video.description}"
    description = meta_tag_description(video.idols.first.name) + description if video.idols.exists?

    meta_tags = {
      site: site_name,
      title: video.title,
      description: description,
      keywords: keywords,
      og: {
        title: :title,
        type: 'website',
        url: "http://www.gravure-tube.xyz/videos/#{video.id}",
        image: video.thumbnail,
        site_name: :site,
        description: :description,
        locale: 'ja_JP'
      },
      twitter: {
        card: "summary",
        site: :site,
        title: :title,
        description: :description,
        image: "http://www.gravure-tube.xyz/videos/#{video.id}" 
      }
    }
  elsif search_result 
    meta_tags = {
      site: site_name,
      title: search_result,
      description: meta_tag_description + "#{search_result}です。",
      keywords: keywords
    }
  else
    meta_tags = {
      site: site_name,
      title: meta_tag_title,
      description: meta_tag_description,
      keywords: keywords,
      og: {
        title: :title,
        type: 'website',
        url: root_url,
        image: image_url('logo.png'),
        site_name: :site,
        description: :description,
        locale: 'ja_JP'
      }
    }
  end

meta name="viewport" content="width=device-width, initial-scale=1"
= display_meta_tags meta_tags

app/views/layouts/_pc_nav_menu.html.slim
ul.right.hide-on-med-and-down
  li
    = link_to 'お問い合わせ', new_contact_path
  li
    = link_to feed_videos_path(format: :rss) do
      i.material-icons
        | settings_input_antenna

app/views/layouts/_sp_nav_menu.html.slim
#slide-out.side-nav
  = form_tag(search_idols_path, method: "get", class: "search-form") do
    .input-field.col.s8
      = text_field_tag 'search', '', placeholder: "グラドル名"
      button.btn.btn-small.btn-search type="submit" name="action"
        i.material-icons
          | search
  ul style="clear:both;"
    li
      = link_to "HOME", root_path
    li
      = link_to "新着動画", root_path(anchor: "video-list")
    li
      = link_to "ランキング", root_path(anchor: "video-ranking")
    li
      = link_to "アイドル一覧", idols_path
a href="#" data-activates="slide-out" class="button-collapse"
  i class="material-icons"
    | menu

app/views/layouts/application.html.slim
doctype html
html
  head
    = stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = render partial: 'layouts/meta_tags', locals: {video: @video, search_result: @result_heading}
    meta name="viewport" content="width=device-width, initial-scale=1"
    javascript:
      var nend_params = {"media":43791,"site":237336,"spot":682723,"type":2,"oriented":1};
    = javascript_include_tag "https://js1.nend.net/js/nendAdLoader.js"
  body
    - if Rails.env.production?
      = render partial: 'layouts/google_analytics'
    #container
      .navbar-fixed
        nav
          .nav-wrapper
            = link_to root_path, class: 'brand-logo' do
              h1.h5 
                | グラビアBOX動画
            = render partial: 'layouts/pc_nav_menu'
            = render partial: 'layouts/sp_nav_menu'
      .row
        h2.h5.red-text.text-lighten-2
          | グラビアBOX動画 〜セクシーグラビア動画見放題!!〜
        #main.col.s12.m12.l8
          = yield
          hr
          .dmm-ranking
            = render partial: "shared/lower_ad"
        #sidebar.col.s12.m12.l4
          = render partial: 'shared/sidebar'

javascript:
  $(".button-collapse").sideNav({
    menuWidth: 250,
    closeOnClick: true,
    draggable: true
  });